### ISSUE TITLE
Wrong flag in help examples/which-key.sh

### ISSUE THREAD

**Issue by ashebanow** [Hyprhook/Hyprhook#5]
## Describe the bug
The help text printed out by -h has a typo. It reads as:

    echo "script usage: $(basename \$0) [-d] [-h]" >&2

and should be:

    echo "script usage: $(basename \$0) [-b] [-h]" >&2

**Comment by Moerliy** [comment]
Appreciate the issue. 
Used it as an excuse to make a better help message overall ;)
